//! Reference re-declaration of the ORACLE's translation catalogs for the
//! `ui/i18n-resolution` court (`cachyos-km-i18n-v1`).
//!
//! Parses the frozen `lang/cachyos-kernel-manager_*.ts` files
//! (`oracle/upstream/lang/`, revision `6b4a373e`) DIRECTLY as XML
//! (roxmltree), and resolves the corpus's (locale, context, source) lookups
//! with the oracle's own semantics:
//!
//! - desired locale = the corpus's `system_locale`;
//! - load order = `initTranslations` (`main.cpp:62-106`): `qt_<base>`,
//!   `qt_<lang_territory>`, app `<base>`, app `<lang_territory>` — the
//!   Qt catalogs are skipped (no Qt runtime);
//! - app catalog keys = the qrc aliases (`cachyoskm_locale.qrc`: the BARE
//!   code, e.g. `de`, `zh-CN`);
//! - `QTranslator::translate(context, source)`: first matching
//!   (context, source) with a non-empty, finished translation, else the
//!   source text.
//!
//! The CANDIDATE resolves via its embedded JSON catalogs (generated by
//! `tools/ts2json.py`); this ref parses the `.ts` directly — the court pins
//! the pipeline fidelity + the resolution semantics. This tool is court
//! evidence infrastructure, never shipped.
//!
//! Usage: i18n-oracle-ref parse <corpus.json>

use serde::Deserialize;
use serde_json::json;
use std::path::PathBuf;
use std::process::ExitCode;

/// `cachyoskm_locale.qrc` <file alias> set (the app catalog keys).
const QRC_ALIASES: &[&str] = &[
    "bg", "ca", "cs", "de", "es", "it", "ja", "ko", "pl", "ru", "sk", "sv", "tr", "nl", "zh-CN",
];

/// Qt's `QString::truncate` at the last `_` (no `_` → unchanged).
fn base_language(lang_territory: &str) -> &str {
    match lang_territory.rfind('_') {
        Some(pos) => &lang_territory[..pos],
        None => lang_territory,
    }
}

/// The load order (`initTranslations`).
fn load_order(system_locale: &str) -> Vec<(String, bool)> {
    let base = base_language(system_locale);
    vec![
        (base.to_string(), true),
        (system_locale.to_string(), true),
        (base.to_string(), false),
        (system_locale.to_string(), false),
    ]
}

/// One parsed `<message>`.
#[derive(Debug, Clone)]
struct Message {
    context: String,
    source: String,
    translation: String,
    unfinished: bool,
}

/// Parse one `.ts` file.
fn parse_ts(path: &std::path::Path) -> Vec<Message> {
    let content = std::fs::read_to_string(path).expect("read .ts");
    let options = roxmltree::ParsingOptions {
        allow_dtd: true, // the .ts files carry a <!DOCTYPE TS>
        ..Default::default()
    };
    let doc = roxmltree::Document::parse_with_options(&content, options).expect("parse .ts xml");
    let mut out = Vec::new();
    for context in doc.descendants().filter(|n| n.has_tag_name("context")) {
        let ctx = context
            .children()
            .find(|n| n.has_tag_name("name"))
            .and_then(|n| n.text())
            .unwrap_or("")
            .to_string();
        for msg in context.children().filter(|n| n.has_tag_name("message")) {
            let source = msg
                .children()
                .find(|n| n.has_tag_name("source"))
                .and_then(|n| n.text())
                .unwrap_or("");
            let (translation, trans_type) = msg
                .children()
                .find(|n| n.has_tag_name("translation"))
                .map(|n| (n.text().unwrap_or("").to_string(), n.attribute("type")))
                .unwrap_or_else(|| (String::new(), None));
            out.push(Message {
                context: ctx.clone(),
                source: source.to_string(),
                translation,
                unfinished: matches!(trans_type, Some("unfinished") | Some("vanished")),
            });
        }
    }
    out
}

/// `QTranslator::translate` over the parsed catalog.
fn translate<'a>(entries: &'a [Message], context: &str, source: &'a str) -> &'a str {
    entries
        .iter()
        .find(|e| e.context == context && e.source == source)
        .filter(|e| !e.unfinished && !e.translation.is_empty())
        .map(|e| e.translation.as_str())
        .unwrap_or(source)
}

#[derive(Debug, Deserialize)]
struct Lookup {
    context: String,
    source: String,
}

#[derive(Debug, Deserialize)]
struct Corpus {
    system_locale: String,
    lookups: Vec<Lookup>,
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let [cmd, path] = args.as_slice() else {
        eprintln!("usage: i18n-oracle-ref parse <corpus.json>");
        return ExitCode::from(2);
    };
    if cmd != "parse" {
        eprintln!("usage: i18n-oracle-ref parse <corpus.json>");
        return ExitCode::from(2);
    }
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let corpus: Corpus = match serde_json::from_str(&content) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };

    // locate the frozen lang/ dir (relative to the repository root)
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest.parent().unwrap().parent().unwrap();
    let lang_dir = repo_root.join("oracle/upstream/lang");

    // the resolved qrc alias: the first non-Qt load-order key that is a
    // compiled alias
    let mut resolved: Option<String> = None;
    for (key, qt) in load_order(&corpus.system_locale) {
        if qt {
            continue;
        }
        if QRC_ALIASES.contains(&key.as_str()) {
            resolved = Some(key);
            break;
        }
    }

    let mut lookups = Vec::new();
    if let Some(alias) = &resolved {
        let ts = lang_dir.join(format!(
            "cachyos-kernel-manager_{}.ts",
            alias // the alias IS the locale name in the file names
        ));
        let entries = parse_ts(&ts);
        for lookup in &corpus.lookups {
            lookups.push(json!({
                "context": lookup.context,
                "source": lookup.source,
                "translation": translate(&entries, &lookup.context, &lookup.source),
            }));
        }
    } else {
        // no catalog: every lookup falls back to the source text
        for lookup in &corpus.lookups {
            lookups.push(json!({
                "context": lookup.context,
                "source": lookup.source,
                "translation": lookup.source,
            }));
        }
    }

    let payload = json!({
        "schema": "cachyos-km-i18n-v1",
        "system_locale": corpus.system_locale,
        "resolved": resolved,
        "lookups": lookups,
    });
    println!(
        "{}",
        serde_json::to_string_pretty(&payload).expect("serialize")
    );
    ExitCode::SUCCESS
}
