#!/usr/bin/env bash
#
# build-candidate-package.sh — assemble the CANDIDATE
# cachyos-kernel-manager package (.pkg.tar.zst) from the LOCAL tree, exactly
# as packaging/PKGBUILD installs it (Phase 10 upgrade/revert courts).
#
# The package replaces the oracle's (same pkgname); the binary is the Rust
# GUI built with --features gui-alpm.
#
# Output: target/cachyos-kernel-manager-0.1.0-1-x86_64.pkg.tar.zst
#
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKGNAME="cachyos-kernel-manager"
PKGVER="0.1.0"
PKGREL="1"
OUT="$ROOT/target/${PKGNAME}-${PKGVER}-${PKGREL}-x86_64.pkg.tar.zst"

echo "== building the release binary (gui-alpm)"
cargo build --manifest-path "$ROOT/Cargo.toml" --release --features gui-alpm --locked

PKGROOT="$(mktemp -d)"
trap 'rm -rf "$PKGROOT"' EXIT
mkdir -p "$PKGROOT/usr/bin" \
    "$PKGROOT/usr/lib/cachyos-kernel-manager" \
    "$PKGROOT/usr/share/applications" \
    "$PKGROOT/usr/share/polkit-1/actions"

# the binary + the shared drop-in files (byte-identical to the oracle's)
install -m755 "$ROOT/target/release/cachyos-kernel-manager" "$PKGROOT/usr/bin/"
install -m755 "$ROOT/packaging/usr/lib/cachyos-kernel-manager/terminal-helper" \
    "$PKGROOT/usr/lib/cachyos-kernel-manager/"
install -m755 "$ROOT/packaging/usr/lib/cachyos-kernel-manager/rootshell.sh" \
    "$PKGROOT/usr/lib/cachyos-kernel-manager/"
install -m644 "$ROOT/packaging/usr/share/applications/org.cachyos.KernelManager.desktop" \
    "$PKGROOT/usr/share/applications/"
install -m644 "$ROOT/packaging/usr/share/polkit-1/actions/org.cachyos.KernelManager.pkexec.policy" \
    "$PKGROOT/usr/share/polkit-1/actions/"
for d in 16x16 22x22 32x32 44x44 48x48 64x64 128x128 150x150 256x256 310x310; do
    install -Dm644 "$ROOT/packaging/usr/share/icons/hicolor/$d/org.cachyos.KernelManager.png" \
        "$PKGROOT/usr/share/icons/hicolor/$d/apps/org.cachyos.KernelManager.png"
done

# the .PKGINFO
cat > "$PKGROOT/.PKGINFO" <<EOF
# Generated by build-candidate-package.sh
pkgname = $PKGNAME
pkgbase = $PKGNAME
pkgver = $PKGVER-$PKGREL
pkgdesc = Native Rust custodial reimplementation of CachyOS Kernel Manager
url = https://github.com/infinityabundance/cachyos-kernel-manager-rs
builddate = $(date +%s)
packager = cachyos-kernel-manager-rs
size = $(du -sb "$PKGROOT/usr" | cut -f1)
arch = x86_64
license = GPL-2.0-or-later
license = GPL-3.0-or-later  # D-009: the code is GPL-2.0-or-later; the binary also links
                            # Slint 1.17.1 (GPL-3.0-or-later or commercial), so the combined
                            # binary is GPL-3.0-or-later
# the chwd dependency (audit P1: the frozen official package depends on it;
# without it the chwd probe silently fails and the NVIDIA expansion changes)
depend = chwd
depend = polkit
depend = scx-manager
depend = pacman
depend = bash
EOF

echo "== assembling $OUT"
bsdtar -cf "$OUT" --format=pax -C "$PKGROOT" .PKGINFO usr
sha256sum "$OUT"
echo "candidate package ready: $OUT"
